2021-06-21 12:32:44,029 ERROR: Exception on /index [GET] [in c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\rmcra\SplonkoReports\app\routes.py", line 49, in index
    return render_template('index.html', title='Home', data=data)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\rmcra\SplonkoReports\app\templates\index.html", line 29, in template
    {{ x.apireason} }}<br> {{ x.statuscode }}
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
2021-06-21 12:33:12,178 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 12:33:31,843 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 12:33:44,057 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 12:33:53,782 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 12:34:12,300 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 13:35:08,565 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 13:35:41,109 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 13:36:09,419 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 13:37:23,836 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 13:38:45,909 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 13:40:05,240 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 13:41:55,651 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 13:42:39,569 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 13:47:56,906 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 13:51:40,121 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 13:52:43,710 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 13:53:27,910 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 13:54:12,450 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 13:56:03,730 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 13:59:19,047 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 13:59:43,998 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 13:59:52,314 ERROR: Exception on /index [GET] [in c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\rmcra\SplonkoReports\app\routes.py", line 49, in index
    return render_template('index.html', title='Home', data=data)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\rmcra\SplonkoReports\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\rmcra\SplonkoReports\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\rmcra\SplonkoReports\app\templates\index.html", line 23, in block 'content'
    <td class="pass"  style="padding: 5px 15px;">{{ pass + 1 }}</td>
jinja2.exceptions.UndefinedError: 'pass' is undefined
2021-06-21 14:00:11,880 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 14:07:35,616 INFO: Splonko startup [in C:\Users\rmcra\SplonkoReports\app\__init__.py:47]
2021-06-21 14:07:43,881 ERROR: Exception on /index [GET] [in c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\rmcra\SplonkoReports\app\routes.py", line 57, in index
    return render_template('index.html', title='Home', data=data, apipass=apipass, apifail=apifail, apitotal=apitotal)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\rmcra\splonkoreports\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\rmcra\SplonkoReports\app\templates\index.html", line 22, in template
    {% endfor %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
