2021-07-03 23:41:58,330 ERROR: Exception on /index [GET] [in /usr/local/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/rmcrave2/PycharmProjects/SplonkoReports/app/routes.py", line 32, in index
    return render_template('index.html', title='Home', stat=stat)
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.9/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/rmcrave2/PycharmProjects/SplonkoReports/app/templates/index.html", line 9, in template
    {% with stat|last as last %}
jinja2.exceptions.TemplateSyntaxError: expected token '=', got '|'
2021-07-03 23:43:16,774 INFO: Splonko startup [in /Users/rmcrave2/PycharmProjects/SplonkoReports/app/__init__.py:47]
2021-07-03 23:43:19,882 ERROR: Exception on /index [GET] [in /usr/local/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/rmcrave2/PycharmProjects/SplonkoReports/app/routes.py", line 32, in index
    return render_template('index.html', title='Home', stat=stat)
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.9/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/rmcrave2/PycharmProjects/SplonkoReports/app/templates/index.html", line 7, in template
    <h1 style="font-family: Ebrima; text-decoration: underline; padding-bottom: 20px; ">  API Dashboard: {{ stat|last.last_updated }}</h1>
jinja2.exceptions.TemplateAssertionError: No filter named 'last.last_updated'.
2021-07-03 23:44:57,171 INFO: Splonko startup [in /Users/rmcrave2/PycharmProjects/SplonkoReports/app/__init__.py:47]
2021-07-03 23:45:01,778 ERROR: Exception on /index [GET] [in /usr/local/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/rmcrave2/PycharmProjects/SplonkoReports/app/routes.py", line 32, in index
    return render_template('index.html', title='Home', stat=stat)
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/rmcrave2/PycharmProjects/SplonkoReports/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/rmcrave2/PycharmProjects/SplonkoReports/app/templates/base.html", line 3, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/usr/local/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/usr/local/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/usr/local/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/usr/local/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/Users/rmcrave2/PycharmProjects/SplonkoReports/app/templates/index.html", line 7, in block 'content'
    <h1 style="font-family: Ebrima; text-decoration: underline; padding-bottom: 20px; ">  API Dashboard: {{ stat.last.last_updated }}</h1>
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'list object' has no attribute 'last'
